pipeline {
    agent any 
	stages {
     stage('git clone') {
        steps {
            git branch: 'main',
                credentialsId: 'Github',
                url: 'https://github.com/nikitha-pallapotu/python_capstone_demo.git'
        }
	}
	 stage('sonar analysis') {
	   steps{
	       script{
	          bat '''
		        call sonar.bat
			   
			   '''
           }
        }
    }	
  }
}

	
