pipeline {
    agent any 
	stages {
     stage('git clone') {
        steps {
            git branch: 'main',
                credentialsId: 'Github',
                url: 'https://github.com/nikitha-pallapotu/python_capstone_demo.git'
        }
	}
	 stage('sonar analysis') {
	   steps{
	       script{
	          bat '''
			    cd python-microservices
		        call sonar.bat
			   
			   '''
           }
        }
    }
      stage('pushing docker image'){
        steps{
            script{
                bat '''
				    cd python-microservices/service1
                    docker build -t nikithap/service1 .	
                    '''	
				}	
            }
        }
	
    }
}

	
