apiVersion: v1
kind: Service
metadata:
  namespace: helloworld
  name: nodeport
spec:
  type: NodePort
  selector:
    app: helloworld
  ports:
     - protocol: TCP
       port: 5050
       targetPort: 5050
       nodePort: 32000
    