apiVersion: v1
kind: Service
metadata:
  namespace: welcome
  name: nodeport2
spec:
  type: NodePort
  selector:
    app: welcome
  ports:
     - protocol: TCP
       port: 5051
       targetPort: 5051
       nodePort: 31000
    