apiVersion: apps/v1
kind: Deployment
metadata: 
   namespace: welcome
   name: service2-deployment
   labels:
      app: welcome
spec:
    template:
        metadata: 
           namespace: welcome
           name: service2-pod
           labels:
              app: welcome
        spec:
            containers:
            - name: welcome
              image: docker.io/nikithap/service2:21     
              ports:
              - containerPort: 5051
              imagePullPolicy: Always  
            imagePullSecrets:
            - name: regcred
    replicas: 2
    selector: 
        matchLabels:
           app: welcome
         